"use strict";
let car = 'subaru';
console.log("Is car == 'subaru'? I predict True.");
console.log(car == 'subaru');
console.log("Is car == 'civic'? I predict false.");
console.log(car == 'civic');
let myAge = '25';
console.log("if age == '25'? ");
console.log(myAge == '25');
console.log("if age == '15'? ");
console.log(myAge == '15');
let myname = 'Anam';
console.log("Is typeof name == 'string'");
console.log(typeof name == 'string');
console.log("Is typeof name != 'string'");
console.log(typeof name != 'string');
let arr = ['a', 'b'];
console.log('arr.length=1');
console.log(arr.length >= 1);
console.log('arr.length=1');
console.log(arr.length > 2);
